# Generated by Django 3.2.5 on 2021-08-07 17:59

from django.db import migrations
from defaults.groups import create_groups


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
